#!/usr/bin/env bun

import * as path from "node:path";
import { Glob } from "bun";

const docsDir = path.resolve(import.meta.dir, "../../../docs");
const outputPath = path.resolve(import.meta.dir, "../src/internal-urls/docs-index.generated.ts");

const glob = new Glob("**/*.md");
const entries: string[] = [];
for await (const relativePath of glob.scan(docsDir)) {
	entries.push(relativePath.split(path.sep).join("/"));
}
entries.sort();

const filenamesLiteral = JSON.stringify(entries);

const output = [
	"// Auto-generated by scripts/generate-docs-index.ts - DO NOT EDIT",
	"// Doc content is read from disk on demand by docs-reader.ts",
	"",
	`export const EMBEDDED_DOC_FILENAMES: readonly string[] = ${filenamesLiteral};`,
	"",
].join("\n");

await Bun.write(outputPath, output);
console.log(`Generated ${path.relative(process.cwd(), outputPath)} (${entries.length} docs)`);
